config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/:repository/forks', to: 'forks#show', as: :forks_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followed_user.rb
class FollowedUser
  attr_reader :all, :screen_name, :profile_pic, :url

  def initialize(attrs)
    @screen_name = attrs[:login]
    @profile_pic = attrs[:avatar_url]
    @url = attrs[:html_url]
  end

  def self.all
    ObjectSpace.each_object(self).to_a
  end
end

app/models/follower.rb
class Follower
  attr_reader :all, :screen_name, :profile_pic, :url
  def initialize(attrs)
    @screen_name = attrs[:login]
    @profile_pic = attrs[:avatar_url]
    @url = attrs[:html_url]
  end

  def self.all
    ObjectSpace.each_object(self).to_a
  end
end

app/models/repository.rb
class Repository
  attr_reader :all, :name, :url, :description, :description,
              :language, :last_updated, :stars, :stars_url, :forks, :starred, :creator, :forked

  def initialize(attrs, starred = false, forked = false)
    @name = attrs[:name]
    @url = attrs[:html_url]
    @description = attrs[:description]
    @language = attrs[:language]
    @last_updated = attrs[:updated_at]
    @stars = attrs[:stargazers_count]
    @stars_url = attrs[:stargazers_url]
    @forks = attrs[:forks_count]
    @starred = starred
    @creator = attrs[:owner][:login]
    @forked = forked
  end


  def self.all
    ObjectSpace.each_object(self).to_a
  end

  def self.starred
    ObjectSpace.each_object(self).to_a.find_all{ |x| x.starred == true}
  end

  def self.forked
    ObjectSpace.each_object(self).to_a.find_all{ |x| x.forked == true}
  end

  def self.find_by_name(name)
    ObjectSpace.each_object(self).to_a.find_all{ |x| x.name == name}
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.screen_name = auth_info.info.nickname
      new_user.oauth_token = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/forks_controller.rb
class ForksController < ApplicationController
  def show
    repository_name = params[:repository_name]
    repository_creator = params[:repository_creator]

    ForkCall.new(current_user, repository_name, repository_creator).forks
    @forked_repositories = Repository.find_by_name(repository_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:tab] == "repositories"
      RepositoryCall.new(current_user).repositories
      @repositories = Repository.all
    elsif params[:tab] == "followers"
      FollowerCall.new(current_user).followers
      @followers = Follower.all
    elsif params[:tab] == "following"
      FollowingCall.new(current_user).following
      @following = FollowedUser.all
    elsif params[:tab] == "stars"
      StarsCall.new(current_user).stars
      @starred_repos = Repository.starred
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forks/show.html.erb
<% @forked_repositories.each do |repository| %>
<li class = "starred_repo">
  <%= link_to "#{repository.creator}/ #{repository.name}", repository.url, { class: 'repo_link'} %><br>
  <span class="repo_description"><%= repository.description %><br></span>
  <span class="repo_language"><%= repository.language %>&nbsp;&nbsp;</span>
  <%= link_to repository.stars, repository.stars_url, { class: 'repo_stars'} %>&nbsp;&nbsp;
  <% if repository.forks > 0 %><%= link_to repository.forks, "/#{repository.name}/forks?creator=#{repository.creator}", { class: 'repo_forks'} %>&nbsp;&nbsp;<% end %>
  <span class="repo_updated_at"><%= repository.last_updated %></span>
</li>
<% end %>

app/views/layouts/_footer.html.erb
© 2018 GitHub, Inc.
<a href="#">Terms</a>
<a href="#">Privacy</a>
<a href="#">Security</a>
<a href="#">Status</a>
<a href="#">Help</a>
<a href="#">Contact GitHub</a>
<a href="#">API</a>
<a href="#">Training</a>
<a href="#">Shop</a>
<a href="#">Blog</a>
<a href="#">About</a>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-github">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="/assets/images/GitHub-Mark-Light-120px-plus.png" alt="Github logo">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search GitHub">
        </div>
        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
      </form>
      <ul class="nav navbar-nav">
        <li><a href="#">
          <%  if current_user %>
          Hello, <%= current_user.screen_name %>
            <%= link_to "Logout", logout_path, method: :delete %>
          <% else %>
            <%= link_to "Login", github_login_path %>
            <% end %></a>
        </li>
        <li class="active"><a href="#">Pull requests<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="#">Issues<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="#">Marketplace<span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="#">Explore<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">New repository</a></li>
            <li><a href="#">Import repository</a></li>
            <li><a href="#">New gist</a></li>
            <li><a href="#">New organization</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubApicurious</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "main" %>
<main>
  <aside class="user-sidebar">
    <img class="profile-pic" src="" alt="">
    <h3>User full name</h3>
    <h4>Username</h4>
    <p>Bio</p>
  </aside>
  <section>
    <div class="User-bar">
      <a href="#">Overview</a>
      <a href="/?tab=repositories">Repositories</a>
      <a href="/?tab=stars">Stars</a>
      <a href="/?tab=followers">Followers</a>
      <a href="/?tab=following">Following</a>
    </div>
    <% if params[:tab] == "repositories" %>
      <ul>
        <% @repositories.each do |repository| %>
        <li>
          <%= link_to repository.name, repository.url %><br>
          <%= repository.description %><br>
          <%= repository.language %>&nbsp;&nbsp;<%= repository.last_updated %>
        </li>
        <% end %>
      </ul>
    <% end %>
    <% if params[:tab] == "followers" %>
      <ul>
        <% @followers.each do |follower| %>
        <li>
          <img src="<%= follower.profile_pic %>" alt="">
          <%= link_to follower.screen_name, follower.url %><br>
        </li>
        <% end %>
      </ul>
    <% end %>
    <% if params[:tab] == "following" %>
      <ul>
        <% @following.each do |followed_user| %>
        <li class="followed_user">
          <img src="<%= followed_user.profile_pic %>" alt="profile-pic">
          <%= link_to followed_user.screen_name, followed_user.url, { class: 'user_screen_name'} %><br>
        </li>
      <% end %>
      </ul>
    <% end %>
    <% if params[:tab] == "stars" %>
      <ul>
        <% @starred_repos.each do |repository| %>
        <li class = "starred_repo">
          <%= link_to "#{repository.creator}/ #{repository.name}", repository.url, { class: 'repo_link'} %><br>
          <span class="repo_description"><%= repository.description %><br></span>
          <span class="repo_language"><%= repository.language %>&nbsp;&nbsp;</span>
          <%= link_to repository.stars, repository.stars_url, { class: 'repo_stars'} %>&nbsp;&nbsp;
          <% if repository.forks > 0 %><%= link_to repository.forks, forks_show_path(repository.name, repository_name: repository.name, repository_creator: repository.creator), { class: 'repo_forks'} %>&nbsp;&nbsp;<% end %>
          <span class="repo_updated_at"><%= repository.last_updated %></span>
        </li>
      <% end %>
      </ul>
    <% end %>
  </section>
</main>